export type Product = {
  id: string;
  name: string;
  brand: string;
  category: "Trail" | "Enduro" | "Downhill" | "E-MTB" | "Youth MTB" | "Accessories" | "Clothing" | "Parts";
  price: number;
  salePrice?: number;
  description: string;
  image: string;
  stock: Record<string, number>; // size: count
  colors: string[];
  sizes: string[];
  specs: Record<string, string>;
  isFeatured?: boolean;
  status: "Active" | "Draft";
  sku: string;
};

export const products: Product[] = [
  {
    id: "trek-slash-8",
    sku: "TRK-SLA-8",
    name: "Slash 8 Gen 6",
    brand: "Trek",
    category: "Enduro",
    price: 4250,
    description: "The Slash 8 is an aluminum enduro mountain bike with a high-pivot suspension design that's built for big trails and bigger hits.",
    image: "/products/trek-slash.jpg",
    stock: { "M": 2, "ML": 3, "L": 2 },
    colors: ["Pennyflake", "Matte Black"],
    sizes: ["S", "M", "ML", "L", "XL"],
    specs: { "Frame": "Alpha Platinum Aluminum", "Travel": "170mm/170mm", "Fork": "RockShox ZEB Select" },
    isFeatured: true,
    status: "Active"
  },
  {
    id: "specialized-stumpjumper-evo",
    sku: "SPZ-STUMP-EVO",
    name: "Stumpjumper EVO Expert",
    brand: "Specialized",
    category: "Trail",
    price: 5500,
    description: "Control, capability, and adjustability. The Stumpjumper EVO is the ultimate trail bike, ready to tackle anything the Peak District throws at it.",
    image: "/products/specialized-stumpjumper.jpg",
    stock: { "S3": 1, "S4": 2 },
    colors: ["Satin Carbon"],
    sizes: ["S1", "S2", "S3", "S4", "S5", "S6"],
    specs: { "Frame": "FACT 11m Carbon", "Travel": "160mm/150mm", "Fork": "Fox Float 36 Performance Elite" },
    isFeatured: true,
    status: "Active"
  },
  {
    id: "santa-cruz-v10",
    sku: "SC-V10-DH",
    name: "Santa Cruz V10 DH",
    brand: "Santa Cruz",
    category: "Downhill",
    price: 8500,
    description: "The winningest bike in downhill history. Re-engineered to be faster and more capable than ever before.",
    image: "/products/santacruz-v10.jpg",
    stock: { "L": 1 },
    colors: ["Red Oxide"],
    sizes: ["S", "M", "L", "XL"],
    specs: { "Frame": "Carbon CC", "Travel": "208mm", "Fork": "Fox 40 Factory" },
    isFeatured: true,
    status: "Active"
  },
  {
    id: "giant-trance-x",
    sku: "GNT-TRX-ADV",
    name: "Trance X Advanced Pro",
    brand: "Giant",
    category: "Trail",
    price: 6499,
    description: "Adjustable geometry and smooth Maestro suspension. A masterpiece of carbon engineering for all-day trail epics.",
    image: "/products/giant-trance.jpg",
    stock: { "M": 2, "L": 1 },
    colors: ["Panther / Gloss Black"],
    sizes: ["S", "M", "L", "XL"],
    specs: { "Frame": "Advanced-Grade Composite", "Travel": "150mm/135mm", "Fork": "Fox 36 Factory" },
    status: "Active"
  },
  {
    id: "whyte-429-v2",
    sku: "WHY-429-V2",
    name: "429 V2 Hardtail",
    brand: "Whyte",
    category: "Trail",
    price: 1150,
    description: "Award-winning geometry and a 120mm travel fork. The ultimate Peak District hardtail.",
    image: "/products/whyte-429.jpg",
    stock: { "M": 5, "L": 4 },
    colors: ["Matt Moss"],
    sizes: ["S", "M", "L", "XL"],
    specs: { "Frame": "Alloy", "Fork": "RockShox Recon" },
    status: "Active"
  },
  {
    id: "trek-fuel-ex-8",
    sku: "TRK-FEX-8",
    name: "Fuel EX 8 Gen 6",
    brand: "Trek",
    category: "Trail",
    price: 3850,
    description: "A versatile trail bike that's ready for anything from Bakewell loops to technical descents.",
    image: "/products/trek-fuel.jpg",
    stock: { "M": 2, "L": 2 },
    colors: ["Matte Black"],
    sizes: ["S", "M", "L", "XL"],
    specs: { "Frame": "Alloy", "Fork": "Fox Rhythm 34" },
    status: "Active"
  },
  {
    id: "orbea-occam-h20",
    sku: "ORB-OCC-H20",
    name: "Occam H20 LT",
    brand: "Orbea",
    category: "Enduro",
    price: 3299,
    description: "The perfect balance between efficiency and rowdy trail performance.",
    image: "/products/orbea-occam.jpg",
    stock: { "M": 1, "L": 1 },
    colors: ["Metallic Mulberry"],
    sizes: ["S", "M", "L", "XL"],
    specs: { "Frame": "Alloy", "Fork": "Fox 36 Performance" },
    status: "Active"
  },
  {
    id: "giant-reign-2",
    sku: "GNT-REI-2",
    name: "Reign 2",
    brand: "Giant",
    category: "Enduro",
    price: 2999,
    description: "Enduro-focused and built for the rowdiest terrain in the Peak District.",
    image: "/products/giant-reign.jpg",
    stock: { "M": 2, "L": 1 },
    colors: ["Black Diamond"],
    sizes: ["S", "M", "L", "XL"],
    specs: { "Frame": "Alloy", "Fork": "RockShox Yari RC" },
    status: "Active"
  },
  {
    id: "transition-sentinel",
    sku: "TRN-SEN-GX",
    name: "Sentinel Carbon GX",
    brand: "Transition",
    category: "Enduro",
    price: 5200,
    description: "The Sentinel has a confidence-inspiring stance that makes you feel like you can conquer anything.",
    image: "/products/transition-sentinel.jpg",
    stock: { "M": 1, "L": 2 },
    colors: ["Ti Grey"],
    sizes: ["S", "M", "L", "XL"],
    specs: { "Frame": "Carbon", "Fork": "RockShox Lyrik Ultimate" },
    status: "Active"
  },
  {
    id: "yeti-sb160",
    sku: "YET-SB160-T3",
    name: "Yeti SB160 T3",
    brand: "Yeti",
    category: "Enduro",
    price: 8900,
    description: "The apex of enduro racing performance. Refined, fast, and uncompromising.",
    image: "/products/yeti-sb160.jpg",
    stock: { "M": 1 },
    colors: ["Turquoise"],
    sizes: ["S", "M", "L", "XL"],
    specs: { "Frame": "Turq Series Carbon", "Fork": "Fox 38 Factory" },
    status: "Active"
  },
  {
    id: "specialized-kenevo-sl",
    sku: "SPZ-KEN-SL",
    name: "Kenevo SL 2 Expert",
    brand: "Specialized",
    category: "E-MTB",
    price: 8500,
    description: "Enduro capability meets lightweight electric power. Redefining what's possible on a climb.",
    image: "/products/specialized-kenevo.jpg",
    stock: { "S3": 1, "S4": 1 },
    colors: ["Gloss Dove Grey"],
    sizes: ["S2", "S3", "S4", "S5"],
    specs: { "Frame": "FACT 11m Carbon", "Motor": "Specialized SL 1.2" },
    status: "Active"
  },
  {
    id: "trek-rail-7",
    sku: "TRK-RAI-7",
    name: "Rail 7 Gen 3",
    brand: "Trek",
    category: "E-MTB",
    price: 5400,
    description: "A long-travel electric mountain bike built for ripping through the most technical Peak District trails.",
    image: "/products/trek-rail.jpg",
    stock: { "M": 1, "L": 1 },
    colors: ["Mercury"],
    sizes: ["S", "M", "L", "XL"],
    specs: { "Frame": "Alloy", "Motor": "Bosch Performance CX" },
    status: "Active"
  },
  {
    id: "giant-fathom-e-2",
    sku: "GNT-FAT-E2",
    name: "Fathom E+ 2",
    brand: "Giant",
    category: "E-MTB",
    price: 2699,
    description: "The perfect introduction to E-MTB riding. Trail-ready and power-packed.",
    image: "/products/giant-fathom.jpg",
    stock: { "M": 2, "L": 2 },
    colors: ["Black"],
    sizes: ["S", "M", "L", "XL"],
    specs: { "Frame": "Alloy", "Motor": "SyncDrive Sport" },
    status: "Active"
  },
  {
    id: "rocky-mountain-reaper",
    sku: "RMB-REA-24",
    name: "Reaper 24",
    brand: "Rocky Mountain",
    category: "Youth MTB",
    price: 1999,
    description: "A real mountain bike for the next generation of shredders.",
    image: "/products/rocky-mountain-reaper.jpg",
    stock: { "24\"": 3 },
    colors: ["Green/Black"],
    sizes: ["24\""],
    specs: { "Frame": "Alloy", "Fork": "Suntour JNR Air" },
    status: "Active"
  },
  {
    id: "early-rider-hellion",
    sku: "ER-HEL-20",
    name: "Hellion 20",
    brand: "Early Rider",
    category: "Youth MTB",
    price: 950,
    description: "The ultimate 20\" hardtail for young trail blazers.",
    image: "/products/early-rider-hellion.jpg",
    stock: { "20\"": 5 },
    colors: ["Brushed Alloy"],
    sizes: ["20\""],
    specs: { "Frame": "Alloy", "Weight": "9.4kg" },
    status: "Active"
  },
  {
    id: "met-trenta-3k",
    sku: "MET-TRN-3K",
    name: "MET Trenta 3K Carbon",
    brand: "MET",
    category: "Accessories",
    price: 270,
    description: "The most advanced road cycling helmet we've ever made.",
    image: "/products/met-trenta.jpg",
    stock: { "M": 10, "L": 5 },
    colors: ["White Carbon"],
    sizes: ["S", "M", "L"],
    specs: { "Type": "Helmet", "Material": "Carbon" },
    status: "Active"
  },
  {
    id: "exposure-strada",
    sku: "EXP-STR-MK12",
    name: "Exposure Strada Mk12 SB",
    brand: "Exposure",
    category: "Accessories",
    price: 315,
    description: "The ultimate road-specific front light.",
    image: "/products/exposure-strada.jpg",
    stock: { "One Size": 12 },
    colors: ["Black"],
    sizes: ["One Size"],
    specs: { "Lumens": "1700", "Battery": "11600mAh" },
    status: "Active"
  },
  {
    id: "hiplok-d1000",
    sku: "HIP-D1000",
    name: "Hiplok D1000 Anti-Angle Grinder Lock",
    brand: "Hiplok",
    category: "Accessories",
    price: 250,
    description: "The world's first portable anti-angle grinder bike lock.",
    image: "/products/hiplok-d1000.jpg",
    stock: { "One Size": 15 },
    colors: ["Black"],
    sizes: ["One Size"],
    specs: { "Rating": "Sold Secure Diamond", "Weight": "1.8kg" },
    status: "Active"
  }
];
